
[project]
dependencies = [
  "fastapi==0.119.0",
  "uvicorn[standard]==0.38.0",
  "sqlalchemy[asyncio]==2.0.41",
  "aiomysql==0.3.2",
  "cryptography>=46.0.3",
  "pydantic==2.12.3",
  "pydantic-settings==2.10.1",
  "loguru==0.7.0",
  "httpx==0.28.1",
]
