# Copyright 2022 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

FROM python:3.12 as fast-base
ENTRYPOINT ["/bin/main.pex"]
COPY src.python.fast/main.pex /bin
